parameters:
    rules:
        '@PhpCsFixer': true
        align_multiline_comment:
            comment_type: all_multiline
        array_indentation: true
        array_push: true
        array_syntax:
            syntax: long
        backtick_to_shell_exec: true
        binary_operator_spaces: true
        blank_line_before_statement:
            statements:
                - break
                - case
                - continue
                - declare
                - default
                - do
                - exit
                - for
                - foreach
                - goto
                - if
                - include
                - include_once
                - require
                - require_once
                - return
                - switch
                - throw
                - try
                - while
                - yield
                - yield_from
        blank_lines_before_namespace: true
        braces_position: true
        control_structure_braces: true
        control_structure_continuation_position:
            position: same_line
        declare_parentheses: true
        statement_indentation: true
        no_multiple_statements_per_line: true
        # Differs from PSR12 but includes it.
        no_extra_blank_lines:
            tokens:
                - break
                - case
                - continue
                - curly_brace_block
                - default
                - extra
                - parenthesis_brace_block
                - return
                - square_brace_block
                - switch
                - throw
                - use
                - use_trait
        cast_spaces:
            space: single
        class_attributes_separation:
            elements:
                const: one
                method: one
                property: one
                trait_import: one
        class_definition:
            multi_line_extends_each_single_line: true
        combine_consecutive_issets: true
        combine_consecutive_unsets: true
        combine_nested_dirname: false
        comment_to_phpdoc: true
        compact_nullable_type_declaration: false
        concat_space:
            spacing: one
        constant_case:
            case: lower
        date_time_immutable: false
        declare_equal_normalize:
            space: none
        declare_strict_types: false
        dir_constant: true
        doctrine_annotation_array_assignment:
            operator: ':'
        doctrine_annotation_braces:
            syntax: without_braces
        doctrine_annotation_indentation: true
        doctrine_annotation_spaces:
            after_argument_assignments: false
            after_array_assignments_colon: true
            after_array_assignments_equals: false
            around_parentheses: true
            before_argument_assignments: false
            before_array_assignments_colon: false
            before_array_assignments_equals: false
        echo_tag_syntax:
            format: long
        elseif: true
        ereg_to_preg: true
        error_suppression:
            mute_deprecation_error: true
            noise_remaining_usages: true
        explicit_indirect_variable: false
        explicit_string_variable: true
        final_class: false
        final_internal_class: true
        final_public_method_for_abstract_class: false
        fopen_flag_order: true
        fopen_flags: true
        fully_qualified_strict_types: true
        function_to_constant: true
        general_phpdoc_annotation_remove:
            annotations:
                - inheritdoc
                - package
                - subpackage
                - author
                - version
        general_phpdoc_tag_rename: true
        global_namespace_import:
            import_classes: true
            import_constants: true
            import_functions: true
        header_comment: false
        heredoc_indentation: false
        heredoc_to_nowdoc: true
        implode_call: true
        include: true
        increment_style:
            style: pre
        indentation_type: true
        integer_literal_case: true
        is_null: true
        linebreak_after_opening_tag: true
        list_syntax: false
        logical_operators: true
        lowercase_static_reference: true
        magic_constant_casing: true
        magic_method_casing: true
        mb_str_functions: false
        method_argument_space:
            on_multiline: ensure_fully_multiline
            keep_multiple_spaces_after_comma: false
        method_chaining_indentation: true
        modernize_types_casting: true
        multiline_comment_opening_closing: true
        multiline_whitespace_before_semicolons:
            strategy: no_multi_line
        native_constant_invocation: true
        native_function_casing: true
        native_function_invocation:
            include:
                - '@compiler_optimized'
            scope: namespaced
            strict: true
        native_type_declaration_casing: true
        new_with_parentheses: true
        no_alias_functions: true
        no_alternative_syntax: true
        no_binary_string: true
        no_blank_lines_after_phpdoc: true
        no_closing_tag: true
        no_empty_comment: true
        no_empty_phpdoc: true
        no_empty_statement: true
        no_homoglyph_names: true
        no_leading_namespace_whitespace: true
        no_mixed_echo_print:
            use: echo
        no_multiline_whitespace_around_double_arrow: true
        no_null_property_initialization: true
        no_php4_constructor: false
        no_short_bool_cast: true
        no_singleline_whitespace_before_semicolons: true
        no_spaces_around_offset:
            positions:
                - inside
                - outside
        no_spaces_after_function_name: true
        no_superfluous_elseif: true
        no_superfluous_phpdoc_tags:
            allow_mixed: true
            allow_unused_params: false
            remove_inheritdoc: true
        no_trailing_comma_in_singleline:
            elements:
                - arguments
                - array_destructuring
                - array
                - group_import
        no_trailing_whitespace: true
        no_trailing_whitespace_in_comment: true
        no_unneeded_braces: true
        no_unneeded_control_parentheses:
            statements:
                - break
                - clone
                - continue
                - echo_print
                - return
                - switch_case
                - yield
        no_unneeded_final_method: true
        no_unreachable_default_argument_value: true
        no_unset_cast: true
        no_unset_on_property: true
        no_unused_imports: true
        no_useless_else: true
        no_useless_return: true
        no_whitespace_before_comma_in_array: true
        no_whitespace_in_blank_line: true
        non_printable_character: true
        normalize_index_brace: true
        not_operator_with_space: false
        not_operator_with_successor_space: false
        nullable_type_declaration_for_default_null_value: true
        object_operator_without_whitespace: true
        # Differs from PSR12 but includes it.
        ordered_class_elements:
            order:
                - use_trait
                - constant_public
                - constant_protected
                - constant_private
                - property_public
                - property_protected
                - property_private
                - construct
                - destruct
                - magic
                - phpunit
                - method_public
                - method_protected
                - method_private
            sort_algorithm: alpha
        ordered_imports:
            imports_order:
                - class
                - function
                - const
            sort_algorithm: alpha
        ordered_interfaces: false
        php_unit_construct:
            assertions:
                - assertSame
                - assertEquals
                - assertNotEquals
                - assertNotSame
        php_unit_dedicate_assert: false
        php_unit_dedicate_assert_internal_type: false
        php_unit_expectation:
            target: newest
        php_unit_fqcn_annotation: true
        php_unit_internal_class:
            types:
                - abstract
                - final
                - normal
        php_unit_method_casing: true
        php_unit_mock: true
        php_unit_mock_short_will_return: true
        php_unit_namespaced:
            target: '5.7'
        php_unit_no_expectation_annotation:
            target: newest
            use_class_const: true
        php_unit_set_up_tear_down_visibility: true
        php_unit_size_class: false
        php_unit_strict: false
        php_unit_test_annotation: true
        php_unit_test_case_static_method_calls:
            call_type: self
        php_unit_test_class_requires_covers: true
        phpdoc_add_missing_param_annotation:
            only_untyped: true
        phpdoc_align: false
        phpdoc_annotation_without_dot: false
        phpdoc_indent: true
        phpdoc_inline_tag_normalizer: true
        phpdoc_line_span:
            const: multi
            property: multi
            method: multi
        phpdoc_no_access: true
        phpdoc_no_alias_tag: true
        phpdoc_no_empty_return: false
        phpdoc_no_package: true
        phpdoc_no_useless_inheritdoc: true
        phpdoc_order: true
        phpdoc_order_by_value: true
        phpdoc_return_self_reference: true
        phpdoc_scalar: true
        phpdoc_separation: true
        phpdoc_single_line_var_spacing: true
        phpdoc_summary: true
        phpdoc_tag_type:
            tags:
                inheritDoc: inline
        phpdoc_to_comment: false
        phpdoc_to_return_type: false
        phpdoc_trim: true
        phpdoc_trim_consecutive_blank_line_separation: true
        phpdoc_types: true
        # Disabled until https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5921 is fixed
        phpdoc_types_order: false
        phpdoc_var_annotation_correct_order: true
        phpdoc_var_without_name: true
        pow_to_exponentiation: true
        protected_to_private: true
        random_api_migration: true
        return_assignment: true
        return_type_declaration:
            space_before: none
        self_accessor: false
        self_static_accessor: true
        semicolon_after_instruction: true
        set_type_to_cast: true
        single_class_element_per_statement:
            elements:
                - const
                - property
        single_blank_line_at_eof: true
        single_import_per_statement: false
        single_line_after_imports: true
        single_line_throw: false
        simple_to_complex_string_variable: true
        simplified_null_return: false
        single_line_comment_style:
            comment_types:
                - hash
        single_quote: true
        single_trait_insert_per_statement: true
        space_after_semicolon: true
        spaces_inside_parentheses: true
        standardize_increment: true
        standardize_not_equals: true
        static_lambda: true
        strict_comparison: true
        strict_param: true
        string_implicit_backslashes: true
        string_length_to_empty: true
        string_line_ending: true
        ternary_to_null_coalescing: false
        trailing_comma_in_multiline: true
        trim_array_spaces: true
        type_declaration_spaces: true
        unary_operator_spaces: true
        void_return: false
        whitespace_after_comma_in_array: true
        yoda_style:
            equal: true
            identical: true
            less_and_greater: true
            always_move_variable: true
